# Frame IDs
odom_frame_id: odom
odom_model_type: diff-corrected
base_frame_id: robot_footprint
global_frame_id: map

# Initial Pose
initial_pose_x: 0.0
initial_pose_y: 0.0
initial_pose_a: -1.57

# Particle Filter Parameters
min_particles: 200
max_particles: 2000

# Movement Thresholds
update_min_d: 0.05
update_min_a: 0.13

# Odometry Model Parameters
odom_alpha1: 0.00001
odom_alpha2: 0.001
odom_alpha3: 0.00001
odom_alpha4: 0.001

# Laser Model Parameters
laser_max_beams: 360 